### ISSUE TITLE
Error message in the console when clicking on Create New Invoice

### ISSUE THREAD

**Issue by CBMR** [Lambda-School-Labs/labspt2-auto-invoicer#126]
**Error message reads:**

`details: "Not a valid origin for the client: https://www.myautoinvoicer.com has not been whitelisted for client ID 959539137198-ehp7h5qhg3ntn9nldvn607n3n0s6t01g.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."
`

**Comment by PaulApivat** [comment]
https://www.myautoinvoicer.com  added to Whitelist

**Comment by PaulApivat** [comment]
issue fixed
